name = "Hammerhead"
uuid = "5ded7e7b-b945-48ee-9a66-c5dce433a0a7"
authors = ["Alex Ames <alexander.m.ames@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
FFTViews = "4f61f5a4-77b1-5117-aa51-3ab5ef4ef0cd"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
FFTViews = "0.3.2"
FFTW = "1.8.1"
ImageFiltering = "0.7.9"
LinearAlgebra = "1.11.0"
LsqFit = "0.15.1"
Statistics = "1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
