name = "Hammerhead"
uuid = "5ded7e7b-b945-48ee-9a66-c5dce433a0a7"
authors = ["Alex Ames <alexander.m.ames@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTViews = "4f61f5a4-77b1-5117-aa51-3ab5ef4ef0cd"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
ChunkSplitters = "3.1.2"
DSP = "0.8.4"
Distributions = "0.25.120"
FFTViews = "0.3.2"
FFTW = "1.8.1"
FileIO = "1.17.0"
GLMakie = "0.13.4"
ImageCore = "0.10.5"
ImageFiltering = "0.7.9"
ImageIO = "0.6.9"
Interpolations = "0.15, 0.16.1"
LinearAlgebra = "1"
LsqFit = "0.15.1"
Statistics = "1"
StructArrays = "0.7.1"
TimerOutputs = "0.5.29"
julia = "1.10"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
